name: "Release Poetry Python Project"
description: "Release a Poetry Python project using semantic-release"

inputs:
  repository:
    description: "The repository to upload your Python package to (e.g., `https://upload.pypi.org/legacy/` for PyPI, or `https://test.pypi.org/legacy/` for Test PyPI)"
    required: false
    default: "https://upload.pypi.org/legacy/"
  pypi_token:
    description: "An API token for the specified PyPI repository"
    required: true
  github_token:
    description: "A GitHub API token (to publish GitHub releases and comment on resolved issues)"
    required: true

runs:
  using: "composite"
  steps:
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: "lts/*"
    - name: Install release dependencies
      shell: bash
      run: npm i --no-save @bjoluc/semantic-release-config-poetry@^$(cat ${{ github.action_path }}/package.json | python3 -c "import sys, json; print(json.load(sys.stdin)['version'])")
    - name: Release
      shell: bash
      env:
        PYPI_REPOSITORY: ${{ inputs.repository }}
        PYPI_TOKEN: ${{ inputs.pypi_token }}
        GITHUB_TOKEN: ${{ inputs.github_token }}
      run: npx semantic-release --extends @bjoluc/semantic-release-config-poetry
